In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# read file
df = pd.read_csv('/content/archive (33).zip')

In [ ]:
df.head()

,gender,age,parental_education_level,family_income,daily_study_hours,attendance_rate,sleep_hours,stress_level,motivation_score,private_tutoring,internet_quality,math_score,reading_score,writing_score,pass_fail
0,Female,15,2,45000.0,2.9,0.916,8.3,6.0,16,False,2,21,29,29,Fail
1,Male,19,2,15000.0,2.8,0.760,6.8,5.0,58,False,3,56,37,45,Fail
2,Female,20,5,55000.0,4.0,0.894,8.2,6.0,51,False,3,60,51,63,Fail
3,Female,16,5,65000.0,4.6,0.888,6.2,6.0,49,False,3,58,54,34,Fail
4,Male,20,4,35000.0,4.3,0.923,7.3,4.0,62,False,2,80,57,73,Pass

In [ ]:
df.tail()

,gender,age,parental_education_level,family_income,daily_study_hours,attendance_rate,sleep_hours,stress_level,motivation_score,private_tutoring,internet_quality,math_score,reading_score,writing_score,pass_fail
199995,Male,18,7,85000.0,7.7,1.000,7.5,7.0,51,True,4,100,97,100,Pass
199996,Female,17,4,65000.0,3.9,0.891,7.2,7.0,55,False,4,46,63,45,Fail
199997,Male,18,4,75000.0,3.2,0.859,7.6,4.0,62,False,4,65,60,58,Pass
199998,Male,21,3,30000.0,4.1,0.950,7.9,5.0,33,False,3,61,77,68,Pass
199999,Male,20,2,35000.0,2.9,0.745,6.7,6.0,36,False,3,44,45,24,Fail

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   gender                    200000 non-null  object
 1   age                       200000 non-null  int64
 2   parental_education_level  200000 non-null  int64
 3   family_income             195975 non-null  float64
 4   daily_study_hours         200000 non-null  float64
 5   attendance_rate           200000 non-null  float64
 6   sleep_hours               195887 non-null  float64
 7   stress_level              196087 non-null  float64
 8   motivation_score          200000 non-null  int64
 9   private_tutoring          200000 non-null  bool
 10  internet_quality          200000 non-null  int64
 11  math_score                200000 non-null  int64
 12  reading_score             200000 non-null  int64
 13  writing_score             200000 non-null  int64
 14  pass_fail                 200000 non-null  object
dtypes: bool(1), float64(5), int64(7), object(2)
memory usage: 21.6+ MB

In [ ]:
df.describe()

,age,parental_education_level,family_income,daily_study_hours,attendance_rate,sleep_hours,stress_level,motivation_score,internet_quality,math_score,reading_score,writing_score
count,200000.000000,200000.000000,195975.000000,200000.000000,200000.000000,195887.000000,196087.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,18.150560,3.692610,51446.026279,3.752547,0.894103,7.706800,5.097166,48.577810,2.912850,62.966925,62.508400,60.997300
std,1.648916,1.611864,36070.995180,0.831978,0.059612,0.930568,1.457824,13.637347,0.722639,17.068637,18.036275,17.138863
min,15.000000,1.000000,15000.000000,2.300000,0.585000,4.000000,1.000000,10.000000,1.000000,0.000000,0.000000,0.000000
25%,17.000000,2.000000,25000.000000,3.200000,0.853000,7.100000,4.000000,39.000000,2.000000,51.000000,50.000000,49.000000
50%,18.000000,4.000000,40000.000000,3.600000,0.895000,7.700000,5.000000,49.000000,3.000000,63.000000,62.000000,61.000000
75%,19.000000,5.000000,65000.000000,4.200000,0.937000,8.300000,6.000000,58.000000,3.000000,75.000000,75.000000,73.000000
max,22.000000,7.000000,400000.000000,8.000000,1.000000,11.000000,10.000000,100.000000,5.000000,100.000000,100.000000,100.000000

In [ ]:
df.shape

(200000, 15)

In [ ]:
df.isnull().sum()

gender                         0
age                            0
parental_education_level       0
family_income               4025
daily_study_hours              0
attendance_rate                0
sleep_hours                 4113
stress_level                3913
motivation_score               0
private_tutoring               0
internet_quality               0
math_score                     0
reading_score                  0
writing_score                  0
pass_fail                      0
dtype: int64

In [ ]:
df['family_income'].fillna(df['family_income'].mean(),inplace= True)

/tmp/ipykernel_1018/2685970568.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['family_income'].fillna(df['family_income'].mean(),inplace= True)

In [ ]:
print(int(df['family_income'].mean()))

51446

In [ ]:
df['sleep_hours']=df['sleep_hours'].fillna(df['sleep_hours'].mode()[0])

In [ ]:
print(df['sleep_hours'].mode())

0    7.7
Name: sleep_hours, dtype: float64

In [ ]:
df['stress_level'] = df['stress_level'].fillna(df['stress_level'].mode()[0])

In [ ]:
print(df['stress_level'].mode())

0    5.0
Name: stress_level, dtype: float64

In [ ]:
df.isnull().sum()

gender                      0
age                         0
parental_education_level    0
family_income               0
daily_study_hours           0
attendance_rate             0
sleep_hours                 0
stress_level                0
motivation_score            0
private_tutoring            0
internet_quality            0
math_score                  0
reading_score               0
writing_score               0
pass_fail                   0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.head()

,gender,age,parental_education_level,family_income,daily_study_hours,attendance_rate,sleep_hours,stress_level,motivation_score,private_tutoring,internet_quality,math_score,reading_score,writing_score,pass_fail
0,Female,15,2,45000.0,2.9,0.916,8.3,6.0,16,False,2,21,29,29,Fail
1,Male,19,2,15000.0,2.8,0.760,6.8,5.0,58,False,3,56,37,45,Fail
2,Female,20,5,55000.0,4.0,0.894,8.2,6.0,51,False,3,60,51,63,Fail
3,Female,16,5,65000.0,4.6,0.888,6.2,6.0,49,False,3,58,54,34,Fail
4,Male,20,4,35000.0,4.3,0.923,7.3,4.0,62,False,2,80,57,73,Pass

In [ ]:
# float  convert to int
print("max:",df['stress_level'].max())
print("min:",df['stress_level'].min())

max: 10.0
min: 1.0

In [ ]:
# float convert to int
print("max:",df['family_income'].max())
print("min:",df['family_income'].min())

max: 400000.0
min: 15000.0

In [ ]:
# float convert to int
print("max:",df['sleep_hours'].max())
print("min:",df['sleep_hours'].min())

max: 11.0
min: 4.0

In [ ]:
#float convert to int
print("max:",df['daily_study_hours'].max())
print("min:",df['daily_study_hours'].min())

max: 8.0
min: 2.3

In [ ]:
# float to percentage
print("max:",df['attendance_rate'].max())
print("min:",df['attendance_rate'].min())

max: 1.0
min: 0.585

In [ ]:
# int value
print("max:",df['reading_score'].max())
print("min:",df['reading_score'].min())

max: 100
min: 0

In [ ]:
# int value
print("max:",df['writing_score'].max())
print("min:",df['writing_score'].min())

max: 100
min: 0

In [ ]:
# int value
print("max:",df['math_score'].max())
print("min:",df['math_score'].min())

max: 100
min: 0

In [ ]:
# int
print("max:",df['motivation_score'].max())
print("min:",df['motivation_score'].min())

max: 100
min: 10

In [ ]:
# int
print("max:",df['age'].max())
print("min:",df['age'].min())

max: 22
min: 15

In [ ]:
# int
print("max:",df['parental_education_level'].max())
print("min:",df['parental_education_level'].min())

max: 7
min: 1

In [ ]:
# float value convert to interger value
df['stress_level'] = df['stress_level'].astype(int)
df['daily_study_hours'] = df['daily_study_hours'].astype(int)
df['sleep_hours'] = df['sleep_hours'].astype(int)
df['family_income'] = df['family_income'].astype(int)
# attendance rate convert to percentage
df['attendance_rate'] = df['attendance_rate']*100

In [ ]:
df

,gender,age,parental_education_level,family_income,daily_study_hours,attendance_rate,sleep_hours,stress_level,motivation_score,private_tutoring,internet_quality,math_score,reading_score,writing_score,pass_fail
0,Female,15,2,45000,2,91.6,8,6,16,False,2,21,29,29,Fail
1,Male,19,2,15000,2,76.0,6,5,58,False,3,56,37,45,Fail
2,Female,20,5,55000,4,89.4,8,6,51,False,3,60,51,63,Fail
3,Female,16,5,65000,4,88.8,6,6,49,False,3,58,54,34,Fail
4,Male,20,4,35000,4,92.3,7,4,62,False,2,80,57,73,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,Male,18,7,85000,7,100.0,7,7,51,True,4,100,97,100,Pass
199996,Female,17,4,65000,3,89.1,7,7,55,False,4,46,63,45,Fail
199997,Male,18,4,75000,3,85.9,7,4,62,False,4,65,60,58,Pass
199998,Male,21,3,30000,4,95.0,7,5,33,False,3,61,77,68,Pass
199999,Male,20,2,35000,2,74.5,6,6,36,False,3,44,45,24,Fail

In [ ]:
df = df.rename(columns={'attendance_rate':'attendance_rate%'})

In [ ]:
df

,gender,age,parental_education_level,family_income,daily_study_hours,attendance_rate%,sleep_hours,stress_level,motivation_score,private_tutoring,internet_quality,math_score,reading_score,writing_score,pass_fail
0,Female,15,2,45000,2,91.6,8,6,16,False,2,21,29,29,Fail
1,Male,19,2,15000,2,76.0,6,5,58,False,3,56,37,45,Fail
2,Female,20,5,55000,4,89.4,8,6,51,False,3,60,51,63,Fail
3,Female,16,5,65000,4,88.8,6,6,49,False,3,58,54,34,Fail
4,Male,20,4,35000,4,92.3,7,4,62,False,2,80,57,73,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,Male,18,7,85000,7,100.0,7,7,51,True,4,100,97,100,Pass
199996,Female,17,4,65000,3,89.1,7,7,55,False,4,46,63,45,Fail
199997,Male,18,4,75000,3,85.9,7,4,62,False,4,65,60,58,Pass
199998,Male,21,3,30000,4,95.0,7,5,33,False,3,61,77,68,Pass
199999,Male,20,2,35000,2,74.5,6,6,36,False,3,44,45,24,Fail

In [ ]:
print(df['gender'].unique())

['Female' 'Male']

In [ ]:
df['gender'].value_counts()

gender
Female    104075
Male       95925
Name: count, dtype: int64

In [ ]:
df.groupby('gender')['attendance_rate%'].value_counts()

gender  attendance_rate%
Female  100.0               4949
        88.7                 707
        87.5                 696
        90.9                 693
        90.7                 692
                            ...
Male    66.5                   1
        67.0                   1
        67.5                   1
        67.6                   1
        68.7                   1
Name: count, Length: 673, dtype: int64

In [ ]:
df.groupby('gender')['age'].agg(lambda x: x.mode().iloc[0])

gender
Female    18
Male      18
Name: age, dtype: int64

In [ ]:
df.groupby('gender')['pass_fail'].value_counts()

gender  pass_fail
Female  Pass         57034
        Fail         47041
Male    Pass         52355
        Fail         43570
Name: count, dtype: int64

In [ ]:
df.groupby('gender')['daily_study_hours'].value_counts().sort_index()

gender  daily_study_hours
Female  2                    16972
        3                    51667
        4                    26929
        5                     6533
        6                     1501
        7                      351
        8                      122
Male    2                    15670
        3                    47382
        4                    24892
        5                     6120
        6                     1398
        7                      343
        8                      120
Name: count, dtype: int64

In [ ]:
df.groupby(['daily_study_hours','attendance_rate%'])['pass_fail'].value_counts()

daily_study_hours  attendance_rate%  pass_fail
2                  59.7              Fail          1
                   62.5              Fail          1
                   64.4              Fail          1
                   65.5              Fail          1
                   66.2              Fail          1
                                                  ..
8                  99.7              Pass          3
                   99.8              Pass          1
                   99.9              Pass          3
                   100.0             Pass         84
                                     Fail          2
Name: count, Length: 2995, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   gender                    200000 non-null  object
 1   age                       200000 non-null  int64
 2   parental_education_level  200000 non-null  int64
 3   family_income             200000 non-null  int64
 4   daily_study_hours         200000 non-null  int64
 5   attendance_rate%          200000 non-null  float64
 6   sleep_hours               200000 non-null  int64
 7   stress_level              200000 non-null  int64
 8   motivation_score          200000 non-null  int64
 9   private_tutoring          200000 non-null  bool
 10  internet_quality          200000 non-null  int64
 11  math_score                200000 non-null  int64
 12  reading_score             200000 non-null  int64
 13  writing_score             200000 non-null  int64
 14  pass_fail                 200000 non-null  object
dtypes: bool(1), float64(1), int64(11), object(2)
memory usage: 21.6+ MB

In [ ]:
df.head()

,gender,age,parental_education_level,family_income,daily_study_hours,attendance_rate%,sleep_hours,stress_level,motivation_score,private_tutoring,internet_quality,math_score,reading_score,writing_score,pass_fail
0,Female,15,2,45000,2,91.6,8,6,16,False,2,21,29,29,Fail
1,Male,19,2,15000,2,76.0,6,5,58,False,3,56,37,45,Fail
2,Female,20,5,55000,4,89.4,8,6,51,False,3,60,51,63,Fail
3,Female,16,5,65000,4,88.8,6,6,49,False,3,58,54,34,Fail
4,Male,20,4,35000,4,92.3,7,4,62,False,2,80,57,73,Pass

In [ ]:
df['age'].value_counts()

age
18    46545
19    41094
17    37645
20    25554
16    21640
15    11410
21    11383
22     4729
Name: count, dtype: int64

In [ ]:
df.to_csv('cleaned_data.csv', index=False)
print('clenedfile_save_successfully')

clenedfile_save_successfully

In [ ]:
#from google.colab import files

files.download('cleaned_data.csv')